certificate_cn: '{{ ansible_site }}.jacobhouse.ca'
certificate_server: tiny.lemarchant.jacobhouse.ca
certificate_server_ssh_fingerprints:
  - tiny.lemarchant.jacobhouse.ca ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNPTpTliUksRtM98tvdCmoC8BiMPTNADaUX0ves5gX6hpxABHaEBAl78wVr3nDO93+Y7DYHukYJTK9ySZg0WSSA= 
  - tiny.lemarchant.jacobhouse.ca ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH91NVbSg1F653TB0mihByoEhUHfdzxKieuAI+AbvONq 
certificates_prefix: /mnt/st1/services
certificates_local_dir: /usr/local/share/certificates
