---
- name: Kubernetes Worker
  hosts: kubernetes_worker
  become: true
  vars_files:
    - inventory/vault.yml
    - "inventory/host_variables/{{ ansible_host }}.yml"
  vars:
    nfs_mounts:
      - server: ritchie
        remote_path: /mnt/default/services
        local_path: /mnt/default/services
        options: rw,sync
  roles:
    - base
    - k3s-worker
